### ISSUE TITLE
can't deploy on heroku?

### ISSUE THREAD

**Issue by harshitethic** [RainEggplant/chatgpt-telegram-bot#2]

**Comment by RainEggplant** [comment]
Is this issue related to browser launching? This program currently needs to run in a headful environment. So if you deploy it to a headless server, you may need to use xvfb to create a virtual display.

**Comment by pawangspandey** [comment]
Hey @RainEggplant 
Can you do an example of may be resources that help to deploy it on a headless server.
I am trying it to deploy on the AWS ec2 machine and also used the xvfb to create the virtual display but don't know How i can attach the virtual display to my local windows laptop to watch the functioning.

Still, after using the xvfb command my login gets rejected (where google login is enabled)

` xvfb-run -a --server-args="-screen 0 1280x800x24 -nolisten tcp -dpi 96 +extension RANDR" npm run start` 

I used above code

Thanks

**Comment by RainEggplant** [comment]
@pawangspandey Sorry for the late reply. I was busy with my course project. You can use [x11vnc](https://stackoverflow.com/questions/12050021/how-to-make-xvfb-display-visible) to connect to the virtual display. The google authentication failure is due to Google's additional verification when you're logging in from a new device. Seems that this [issue](https://github.com/transitive-bullshit/chatgpt-api/issues/188) hasn't been fixed yet.

I will add this information to the README later.
